@extends('layouts.master')

@section('css')
<script src="{{ asset('js/level-get-data-room.js') }}" defer></script>
@endsection
@section('content')
@auth
<div align="center">
    <!-- Image Map Generated by http://www.image-map.net/ -->
    <img src="https://raw.githubusercontent.com/Naphorn/ProjectMA/master/resources/views/images/level2.png" usemap="#image-map">

    <map name="image-map">
        <area target="" alt="IE3219" title="IE3219" onclick="ajax_get_data_room_detail('IE3219')" coords="421,21,545,95" shape="rect">
        <area target="" alt="IE3218" title="IE3218" onclick="ajax_get_data_room_detail('IE3218')" coords="421,96,495,120" shape="rect">
        <area target="" alt="IE3217" title="IE3217" onclick="ajax_get_data_room_detail('IE3217')" coords="420,120,495,169" shape="rect">
        <area target="" alt="IE3216" title="IE3216" onclick="ajax_get_data_room_detail('IE3216')" coords="420,171,495,219" shape="rect">
        <area target="" alt="IE3215" title="IE3215" onclick="ajax_get_data_room_detail('IE3215')" coords="420,220,495,244" shape="rect">
        <area target="" alt="IE3214" title="IE3214" onclick="ajax_get_data_room_detail('IE3214')" coords="421,245,495,294" shape="rect">
        <area target="" alt="IE3213" title="IE3213" onclick="ajax_get_data_room_detail('IE3213')" coords="420,295,495,319" shape="rect">
        <area target="" alt="IE3212" title="IE3212" onclick="ajax_get_data_room_detail('IE3212')" coords="420,320,495,369" shape="rect">
        <area target="" alt="IE3211" title="IE3211" onclick="ajax_get_data_room_detail('IE3211')" coords="346,471,395,570" shape="rect">
        <area target="" alt="IE3210" title="IE3210" onclick="ajax_get_data_room_detail('IE3210')" coords="295,471,345,569" shape="rect">
        <area target="" alt="IE3209" title="IE3209" onclick="ajax_get_data_room_detail('IE3209')" coords="145,471,294,569" shape="rect">
        <area target="" alt="IE3208" title="IE3208" onclick="ajax_get_data_room_detail('IE3208')" coords="296,370,420,419" shape="rect">
        <area target="" alt="IE3207" title="IE3207" onclick="ajax_get_data_room_detail('IE3207')" coords="220,370,295,419" shape="rect">
        <area target="" alt="IE3206" title="IE3206" onclick="ajax_get_data_room_detail('IE3206')" coords="146,371,219,419" shape="rect">
        <area target="" alt="IE3205" title="IE3205" onclick="ajax_get_data_room_detail('IE3205')" coords="95,321,144,395" shape="rect">
        <area target="" alt="IE3204" title="IE3204" onclick="ajax_get_data_room_detail('IE3204')" coords="20,320,94,469" shape="rect">
        <area target="" alt="IE3203" title="IE3203" onclick="ajax_get_data_room_detail('IE3203')" coords="20,471,94,494" shape="rect">
        <area target="" alt="IE3202" title="IE3202" onclick="ajax_get_data_room_detail('IE3202')" coords="20,496,94,644" shape="rect">
        <area target="" alt="IE3201" title="IE3201" onclick="ajax_get_data_room_detail('IE3201')" coords="20,646,94,694" shape="rect">
        <area target="" alt="IE2201" title="IE2201" onclick="ajax_get_data_room_detail('IE2201')" coords="397,871,495,994" shape="rect">
        <area target="" alt="IE2202" title="IE2202" onclick="ajax_get_data_room_detail('IE2202')" coords="346,833,394,907" shape="rect">
        <area target="" alt="IE2203" title="IE2203" onclick="ajax_get_data_room_detail('IE2203')" coords="20,745,94,795" shape="rect">
        <area target="" alt="IE2204" title="IE2204" onclick="ajax_get_data_room_detail('IE2204')" coords="145,745,195,794" shape="rect">
        <area target="" alt="IE2205" title="IE2205" onclick="ajax_get_data_room_detail('IE2205')" coords="196,745,246,795" shape="rect">
        <area target="" alt="IE2206" title="IE2206" onclick="ajax_get_data_room_detail('IE2206')" coords="247,745,296,794" shape="rect">
        <area target="" alt="IE2207" title="IE2207" onclick="ajax_get_data_room_detail('IE2207')" coords="298,745,397,794" shape="rect">
        <area target="" alt="IE2208" title="IE2208" onclick="ajax_get_data_room_detail('IE2208')" coords="545,746,721,746,721,695,821,696,822,844,785,845,785,870,545,870" shape="poly">
        <area target="" alt="IE2209" title="IE2209" onclick="ajax_get_data_room_detail('IE2209')" coords="420,721,496,745" shape="rect">
        <area target="" alt="IE2210" title="IE2210" onclick="ajax_get_data_room_detail('IE2210')" coords="422,621,495,719" shape="rect">
        <area target="" alt="IE2211" title="IE2211" onclick="ajax_get_data_room_detail('IE2211')" coords="422,521,495,619" shape="rect">
        <area target="" alt="IE2212" title="IE2212" onclick="ajax_get_data_room_detail('IE2212')" coords="545,521,595,594" shape="rect">
        <area target="" alt="IE2213" title="IE2213" onclick="ajax_get_data_room_detail('IE2213')" coords="596,521,646,594" shape="rect">
        <area target="" alt="IE2214" title="IE2214" onclick="ajax_get_data_room_detail('IE2214')" coords="647,521,721,594" shape="rect">
        <area target="" alt="IE2215" title="IE2215" onclick="ajax_get_data_room_detail('IE2215')" coords="722,520,822,595" shape="rect">
        <area target="" alt="IE2216" title="IE2216" onclick="ajax_get_data_room_detail('IE2216')" coords="747,595,822,645" shape="rect">
        <area target="" alt="IE2217" title="IE2217" onclick="ajax_get_data_room_detail('IE2217')" coords="747,645,821,694" shape="rect">
        <area target="" alt="IE1202" title="IE1202" onclick="ajax_get_data_room_detail('IE1202')" coords="711,908,785,1032" shape="rect">
        <area target="" alt="IE1201" title="IE1201" onclick="ajax_get_data_room_detail('IE1201')" coords="610,1122,708,1122,709,1148,783,1147,784,1296,634,1296,633,1271,610,1272" shape="poly">
    </map>
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Status</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            </div>
        </div>
    </div>
    {{-- ---------------------------------------------------------------------------------------------- --}}
        <!-- Modal -->
        <div class="modal fade" id="modal" role="dialog">
            <!-- <form method="POST" id="form-promote"> -->
            <form class="tagForm" id="tag-form" action="" method="post" enctype="multipart/form-data">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body">



                    </div>
                    <div class="modal-footer">
                        <!-- <button type="submit" class="btn btn-primary">Send</button> -->
                        <input id="tag-form-submit" type="submit" class="btn btn-primary" value="Send">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
    {{-- ---------------------------------------------------------------------------------------------- --}}
</div>
@endauth
@endsection
